//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleMonReportN
    {
        public int RowIndex { get; set; }
        public string 廢棄物來源是否為事業單位 { get; set; }
        public string 委託單位名稱 { get; set; }
        public string 委託單位證號 { get; set; }
        public string 委託單位地址 { get; set; }
        public string 縣市別代碼 { get; set; }
        public string 行業別代碼 { get; set; }
        public string 六聯單單號 { get; set; }
        public int 廢棄物編號 { get; set; }
        public float 清除量 { get; set; }
        public System.DateTime 清除日期 { get; set; }
        public string 清除方法 { get; set; }
        public string 貯存地點 { get; set; }
        public string 中間或最終處置地點代碼 { get; set; }
        public System.DateTime 中間或最終處置到達日期 { get; set; }
        public string 清運_x0028_除_x0029_機具車號 { get; set; }
        public string 清運_x0028_除_x0029_機具拖車車尾車號 { get; set; }
    }
}
